# Note (epaulki) Don't use container_name here as it will break CI's testRunner.sh script.

version: "2"

services:

  # Image Containing DPS and the Model Repo
  mysql:
    container_name: mysql_container
    image: mysql/mysql-server:latest
    environment:
       # - MYSQL_USER=root
      #  - MYSQL_PASSWORD=root
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=footiedb
    volumes:
      - ./databaseSql/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
